### ISSUE TITLE
Asynchronous Distribution (activemq)

### ISSUE THREAD

**Issue by timosalex** [BroadleafCommerce/DemoSite#47]
Hello,

not an issue just looking for a tip from the community here on how to configure broadleaf to work with activemq.

I have installed activemq and set  reliableAsync to true on emailInfo

`    info.setSendEmailReliableAsync("true");  `

I am getting this error 

`org.broadleafcommerce.common.email.service.exception.EmailException: The property sendEmailReliableAsync on EmailInfo is true, but the EmailService does not have an instance of JMSEmailServiceProducer set.
`

As far as I understand I have to set JMSEmailServiceProducer inside blEmailINfo() (at core-CoreEmailConfig).
It is unclear to me how i put a destination there  as it is described on the xml [approach ](https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/additional-configuration/email-configuration)

any tips would be really helpful!!
thanks in advance

**Comment by cja769** [comment]
You'll notice in `EmailServiceImpl` that the `EmailServiceProducer` is not injected by bean. In my opinion it should be injected as an optional dependency however currently it is not injected at all. You'll need to set the `emailServiceProducer` property on `EmailServiceImpl` manually. Since the `EmailServiceImpl` is created as a bean through component scanning you'll either have to inject the `blEmailService` into your `CoreEmailConfig` and set the `emailServiceProducer` property when creating the `EmailServiceProducer` (the `blEmailService` bean is a singleton so by setting it there it'll be set for the whole application) or redefine the `blEmailService` bean in the `CoreEmailConfig` and set the property there. I'd probably go with the second option since it's a bit less hacky. I'll get a PR built to optionally inject the `EmailServiceProducer` since that's the correct way this should be setup.

**Comment by timosalex** [comment]
@cja769  thanks for your response. I am trying to follow the second option of your advice. So in CoreEmailConfig I don't see any `blEmailService ` bean.  If I inject it myself how to set the property? This is where i am little lost, maybe a really small example would help :)
thanks again!

**Comment by cja769** [comment]
@timosalex Like I said, I would suggest doing my second option since it's a little less hacky. Basically this would be the code

```
// Your definition of the EmailServiceProducer is somewhere in this configuration class.
// Lets say that you named the method emailServiceProducer
@Bean
public EmailService blEmailService() {
    EmailServiceImpl emailService = new EmailServiceImpl();
    emailService.setEmailServiceProducer(emailServiceProducer());
    return emailService;
}
```

However if you want to do it the other way this is what I was thinking

```
@Resource("blEmailService")
protected EmailService emailService;

@Bean
public EmailServiceProducer emailServiceProducer() {
    EmailServiceProducer producer = // create producer;
    ((EmailServiceImpl) emailService).setEmailServiceProducer(producer);
    return producer;
}
```

I say the second way is hacky because modifying singleton beans is hacky and just creating it in the way you prefer is much cleaner but both options should work.

**Comment by timosalex** [comment]
@cja769 thanks a ton for all the help. So I am here at the moment. I added this bean (as you descibe) in CoreEmailConfig

```
  @Bean
    public EmailService blEmailService() {
        EmailServiceImpl emailService = new EmailServiceImpl();
        emailService.setEmailServiceProducer(emailServiceProducer());
        return emailService;
    }
```

Now I am trying to create emailServiceProducer() method. I did this:

```
public JMSEmailServiceProducerImpl emailServiceProducer() {
    	JMSEmailServiceProducerImpl producer=new JMSEmailServiceProducerImpl() ; // create producer;
        		producer.setEmailServiceTemplate(jmsTemplate());
        		
        return producer;
    }

    public JmsTemplate jmsTemplate(){
        JmsTemplate template = new JmsTemplate();
        template.setConnectionFactory(connectionFactory());
        template.setDefaultDestinationName("what to put here??");
        return template;
    }
    public ConnectionFactory cachingConnectionFactory(){
        CachingConnectionFactory connectionFactory = new CachingConnectionFactory();
        connectionFactory.setTargetConnectionFactory(connectionFactory());
        connectionFactory.setSessionCacheSize(10);
        return connectionFactory;
    }
    
    public ConnectionFactory connectionFactory(){
        ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactory();
        connectionFactory.setBrokerURL("tcp://localhost:61616");
	    connectionFactory.setPassword("admin");
	    connectionFactory.setUserName("admin");

        return connectionFactory;
    }


```

I get the error now 

`java.lang.UnsupportedOperationException: A destination must be specified.
`
What do you think about the above code? 
I am trying to find the analogy between the xml configuration on broadleaf documentation so I am confused as to what put in this line:

`        template.setDefaultDestinationName("what to put here??");
`

Once again thanks a ton for all the help and possible tips!

**Comment by cja769** [comment]
@timosalex If you take a look inside `JMSEmailServiceProducerImpl` you'll see there's a property `emailServiceDestination` and it's required to be non-null.

On a side note, I committed the change to autowire the `EmailServiceProducer` into `EmailServiceImpl` so you should be able to just create your `EmailServiceProducer` as a bean and you won't need
```
@Bean
    public EmailService blEmailService() {
        EmailServiceImpl emailService = new EmailServiceImpl();
        emailService.setEmailServiceProducer(emailServiceProducer());
        return emailService;
    }
```
anymore. Make sure you're targeting BLC 6.0.1-SNAPSHOT to get that change.
