### ISSUE TITLE
An error occurred while processing your request.  Deployed 6

### ISSUE THREAD

**Issue by rcampion** [BroadleafCommerce/DemoSite#54]
Alert Message:   An error occurred while processing your request.
Deployed 6.0.3-GA to Tomcat 8 as a war.  
Happens when you try to add a product to the cart.

**Comment by cja769** [comment]
Hi @rcampion was there a stacktrace or any other errors that may state a cause of some sort? Also the newest version of 6.0.x out is 6.0.4-GA. Can you test with that version to see if the error still occurs? Thanks

**Comment by rcampion** [comment]
There was nothing in catalina.out log.  I tested it with 6.0.5-SNAPSHOT, same error.  I reverted to the old templates, new js, problem does not occur.  I wish I could be of more help.  I think the error comes from BLC.js.

**Comment by cja769** [comment]
@rcampion I was able to reproduce this error and got an exception in `catalina.out` that the CSRF token didn't match. This occurs because there's some other configuration that needs to be done. Please refer to our tomcat setup [here](https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/key-aspects-and-configuration/app-server-configuration/tomcat). I'm still having issues checking out because it looks like the JS isn't loading correctly on that page and I'm currently looking into that.

**Comment by rcampion** [comment]
I think I found the problem.  In cartOperations.js, function Cart.updateMiniCart, the url is hardcoded to /cart/mini,  I deploy my war file, shop,war so it has a context of /shop.  I hardcoded the url to /shop/cart/mini and I no longer get an error.
